title: On Retainer
description: Legal Intelligence for Australian Founders and SMEs
url: "https://onretainer.com.au"

theme: null
markdown: kramdown
permalink: /Intelligence/:slug.html

collections:
  articles:
    output: true
    permalink: /Intelligence/:slug.html

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
